app = "minha-api"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  force_https = true

  [[services.ports]]
    port = "80"
  [[services.ports]]
    port = "443"

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
